import type { RepoAnalysis } from "../types.js";
import { bulletList, valueOrUnknown } from "./format.js";

export function generateProjectMd(analysis: RepoAnalysis): string {
  return `# Project Notes

Generated by \`agent-notes\`.

## Detected Project Type

${bulletList(analysis.projectTypes)}

## Detected Languages

${bulletList(analysis.languages)}

## Detected Frameworks

${bulletList(analysis.frameworks)}

## Detected Workspaces

${formatWorkspaces(analysis)}

## Detected Package Manager

- ${valueOrUnknown(analysis.packageManager)}

## Important Files

${bulletList(analysis.importantFiles)}

## Warnings

${bulletList(analysis.warnings)}
`;
}

function formatWorkspaces(analysis: RepoAnalysis): string {
  if (!analysis.workspaces) {
    return "- none detected";
  }

  const lines = [
    "Patterns:",
    ...analysis.workspaces.patterns.map((pattern) => `- \`${pattern}\``),
    "",
    "Packages:",
    ...analysis.workspaces.packages.map((workspacePackage) => {
      const name = workspacePackage.name ? ` (\`${workspacePackage.name}\`)` : "";
      return `- ${workspacePackage.path}${name}`;
    })
  ];

  return lines.join("\n");
}
