import type { RepoAnalysis } from "../types.js";
import { bulletList, valueOrUnknown } from "./format.js";

export function generateProjectMd(analysis: RepoAnalysis): string {
  return `# Project Notes

Generated by \`agent-notes\`.

## Detected Project Type

${bulletList(analysis.projectTypes)}

## Detected Languages

${bulletList(analysis.languages)}

## Detected Frameworks

${bulletList(analysis.frameworks)}

## Detected Package Manager

- ${valueOrUnknown(analysis.packageManager)}

## Important Files

${bulletList(analysis.importantFiles)}

## Warnings

${bulletList(analysis.warnings)}
`;
}
